# Generated by Django 4.0.4 on 2022-04-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='response',
            field=models.TextField(default='this is an answer'),
        ),
    ]
